export const mixedCases: { label: string; text: string; expectRomanized: boolean }[] = [
  // ═══ Hinglish — Hindi-English code-mixing (expectRomanized: true) ═══
  { label: 'Hinglish 1', text: "yaar let's go to the mall bahut maza aayega shopping karenge saath mein", expectRomanized: true },
  { label: 'Hinglish 2', text: "office mein kaam bahut zyada hai boss ne bola overtime karo aaj raat ko", expectRomanized: true },
  { label: 'Hinglish 3', text: "mujhe lagta hai yeh movie bahut boring hai let's watch something else please yaar", expectRomanized: true },
  { label: 'Hinglish 4', text: "kal meeting mein bahut drama hua everyone was fighting over the budget allocation bhai", expectRomanized: true },
  { label: 'Hinglish 5', text: "bhai pizza order karo na bahut bhookh lagi hai extra cheese ke saath please", expectRomanized: true },
  { label: 'Hinglish 6', text: "exam bahut tough tha yaar I think I might fail this time padhai nahi ki thi", expectRomanized: true },
  { label: 'Hinglish 7', text: "aaj weather bahut achha hai let's go for a walk park mein chalte hain yaar", expectRomanized: true },
  { label: 'Hinglish 8', text: "meri car kharab ho gayi hai need to take it to the mechanic jaldi se fix karao", expectRomanized: true },
  { label: 'Hinglish 9', text: "ghar pe koi nahi hai sab bahar gaye hain I am so bored kuch karte hain yaar", expectRomanized: true },
  { label: 'Hinglish 10', text: "party mein bahut maza aaya music bhi achha tha everyone danced till midnight kal raat", expectRomanized: true },
  { label: 'Hinglish 11', text: "mere dost ka birthday hai next week uske liye kuch special plan karte hain gift bhi lana hai", expectRomanized: true },
  { label: 'Hinglish 12', text: "bahut garmi hai yaar let's get some ice cream parlour chalte hain thanda kuch khaate hain", expectRomanized: true },
  { label: 'Hinglish 13', text: "maa ne bola dinner ready hai come home jaldi se khana thanda ho raha hai abhi aao", expectRomanized: true },
  { label: 'Hinglish 14', text: "ye assignment bahut mushkil hai I need help koi help karega kya please yaar batao toh", expectRomanized: true },
  { label: 'Hinglish 15', text: "train late hai yaar thirty minutes delay hai platform pe bahut crowd hai aaj phir se", expectRomanized: true },
  { label: 'Hinglish 16', text: "shaadi mein bahut fun tha DJ played amazing songs sab ne bahut dance kiya raat bhar", expectRomanized: true },
  { label: 'Hinglish 17', text: "gym jaana hai kal se start karte hain need to get fit bahut mota ho gaya hoon", expectRomanized: true },
  { label: 'Hinglish 18', text: "aaj subah chai nahi mili coffee shop band tha bahut bura laga without chai morning mein", expectRomanized: true },
  { label: 'Hinglish 19', text: "kya plan hai weekend ka let's go somewhere nice thoda bahar ghoomte hain change ke liye", expectRomanized: true },
  { label: 'Hinglish 20', text: "landlord ne rent badha diya yaar bahut expensive ho gaya hai this city is too costly ab", expectRomanized: true },
  { label: 'Hinglish 21', text: "project deadline kal hai aur abhi tak start nahi kiya bahut tension hai yaar help me please", expectRomanized: true },
  { label: 'Hinglish 22', text: "uber book karo jaldi se late ho rahe hain meeting ke liye bahut traffic hai road pe", expectRomanized: true },
  { label: 'Hinglish 23', text: "meri phone ki battery khatam ho gayi hai charger nahi hai does anyone have an extra one yaar", expectRomanized: true },
  { label: 'Hinglish 24', text: "kal cricket match hai India vs Australia dekhnege saath mein bahut excited hoon sab aao yaar", expectRomanized: true },
  { label: 'Hinglish 25', text: "papa ne nayi car book ki hai next month delivery hai bahut khush hain sab ghar mein wow", expectRomanized: true },
  { label: 'Hinglish 26', text: "interview achha gaya I think they liked me bahut confident feel hua fingers crossed ab result ka", expectRomanized: true },
  { label: 'Hinglish 27', text: "baarish ho rahi hai bahar mat jao umbrella nahi hai you will get wet pura bheeg jaoge", expectRomanized: true },
  { label: 'Hinglish 28', text: "chai aur samosa khaate hain canteen mein best combo hai office ke break mein roz khaata hoon", expectRomanized: true },
  { label: 'Hinglish 29', text: "holiday plan karna hai Goa chalte hain beach pe maza aayega bahut let's book tickets jaldi", expectRomanized: true },
  { label: 'Hinglish 30', text: "salary aa gayi finally bahut din se wait kar raha tha shopping karni hai aaj raat ko", expectRomanized: true },

  // ═══ Arabizi — Arabic-English code-mixing (expectRomanized: true) ═══
  { label: 'Arabizi 1', text: "yalla let's go habibi the party is amazing wallah I'm having so much fun tonight", expectRomanized: true },
  { label: 'Arabizi 2', text: "inshallah tomorrow will be better ya akhi today was really tough at work khalas enough", expectRomanized: true },
  { label: 'Arabizi 3', text: "wallah the food was amazing habibi you have to try the shawarma it's the best mashallah", expectRomanized: true },
  { label: 'Arabizi 4', text: "ana coming late today sorry habibi traffic is crazy yalla I'll be there soon inshallah", expectRomanized: true },
  { label: 'Arabizi 5', text: "shukran for helping me ya sadeeqi I really appreciate it mashallah you are the best friend", expectRomanized: true },
  { label: 'Arabizi 6', text: "the weather is so nice today alhamdulillah let's go for a walk ya habibi yalla", expectRomanized: true },
  { label: 'Arabizi 7', text: "khalas I'm done with this project wallah it took so long ya akhi but finally finished", expectRomanized: true },
  { label: 'Arabizi 8', text: "ya zalameh this movie is so boring wallah let's watch something else habibi change it now", expectRomanized: true },
  { label: 'Arabizi 9', text: "ana miss you so much ya habibi when are you coming back inshallah soon wallah", expectRomanized: true },
  { label: 'Arabizi 10', text: "the exam was easy alhamdulillah studied hard wallah hope I pass inshallah ya rab ameen", expectRomanized: true },
  { label: 'Arabizi 11', text: "mashi ya akhi I understand the situation khalas let's move on habibi no worries about it", expectRomanized: true },
  { label: 'Arabizi 12', text: "let's meet at the cafe ya habibi I know a great place ahlan wa sahlan bikum all", expectRomanized: true },
  { label: 'Arabizi 13', text: "ya salam this view is incredible mashallah the sunset over the sea is breathtaking wallah", expectRomanized: true },
  { label: 'Arabizi 14', text: "sorry habibi I forgot to call you wallah I was so busy at work mashallah forgive me", expectRomanized: true },
  { label: 'Arabizi 15', text: "the wedding was beautiful mashallah the bride and groom looked amazing yalla let's dance habibi", expectRomanized: true },

  // ═══ Spanglish — Spanish-English code-mixing (expectRomanized: false) ═══
  { label: 'Spanglish 1', text: "vamos to the store necesito comprar some groceries para la casa antes de que cierren", expectRomanized: false },
  { label: 'Spanglish 2', text: "my mom hizo tamales ayer y estaban super delicious quieres que te traiga algunos tomorrow", expectRomanized: false },
  { label: 'Spanglish 3', text: "oye I need to tell you algo importante but not right now despues hablamos vale amigo", expectRomanized: false },
  { label: 'Spanglish 4', text: "el meeting fue super boring pero at least we got a raise finalmente despues de tanto tiempo", expectRomanized: false },
  { label: 'Spanglish 5', text: "let me call mi abuela because she wants to know cuando llegamos a su casa esta tarde", expectRomanized: false },
  { label: 'Spanglish 6', text: "we're going al parque this weekend con los kids they love playing outside en el sol", expectRomanized: false },
  { label: 'Spanglish 7', text: "necesito un coffee asap estoy super cansada from working all night on this proyecto grande", expectRomanized: false },
  { label: 'Spanglish 8', text: "my tio tiene una fiesta grande this Saturday y todos estan invited vengan con familia por favor", expectRomanized: false },
  { label: 'Spanglish 9', text: "la musica at the concert was increible they played salsa merengue and some pop songs too", expectRomanized: false },
  { label: 'Spanglish 10', text: "he told me que ya no quiere ir but I think he's lying porque siempre dice lo mismo", expectRomanized: false },
  { label: 'Spanglish 11', text: "this barrio has the best food trucks con tacos al pastor y elotes con crema delicioso", expectRomanized: false },
  { label: 'Spanglish 12', text: "vamos a comer before the movie starts because tengo mucha hambre y no quiero snacks caros", expectRomanized: false },
  { label: 'Spanglish 13', text: "my prima got married last weekend y la boda was so beautiful todo el mundo estuvo feliz", expectRomanized: false },
  { label: 'Spanglish 14', text: "I forgot mi telefono en casa and now I can't call nadie tengo que regresar rapido", expectRomanized: false },
  { label: 'Spanglish 15', text: "estoy looking for a new apartment porque este is too small necesito mas espacio para trabajar", expectRomanized: false },

  // ═══ English with many loanwords (expectRomanized: false) ═══
  { label: 'EN loan 1', text: "the tikka masala with naan bread and raita was absolutely delicious at the restaurant tonight", expectRomanized: false },
  { label: 'EN loan 2', text: "the dojo offers karate and judo classes for beginners every tuesday and thursday evening sessions", expectRomanized: false },
  { label: 'EN loan 3', text: "she wore a beautiful sari with intricate embroidery to the diwali festival celebration downtown", expectRomanized: false },
  { label: 'EN loan 4', text: "the sushi chef made the most amazing nigiri and sashimi platter with wasabi and ginger on side", expectRomanized: false },
  { label: 'EN loan 5', text: "we practiced yoga and meditation at the ashram followed by a session of pranayama breathing exercises", expectRomanized: false },
  { label: 'EN loan 6', text: "the ramen shop serves tonkotsu broth with chashu pork and ajitama eggs it is incredibly flavorful", expectRomanized: false },
  { label: 'EN loan 7', text: "the bazaar in the old city sells beautiful kilim rugs and handcrafted lanterns from artisan makers", expectRomanized: false },
  { label: 'EN loan 8', text: "we went to the biergarten and ordered bratwurst pretzels and a stein of weissbier for dinner", expectRomanized: false },
  { label: 'EN loan 9', text: "the feng shui consultant recommended moving the sofa and adding bamboo plants for better chi flow", expectRomanized: false },
  { label: 'EN loan 10', text: "he practices tai chi every morning in the park with a group of senior citizens from the community", expectRomanized: false },
  { label: 'EN loan 11', text: "the restaurant serves excellent hummus falafel shawarma and tabbouleh with fresh pita bread on the side", expectRomanized: false },
  { label: 'EN loan 12', text: "she studied kung fu and aikido for years and can demonstrate several advanced kata sequences perfectly", expectRomanized: false },
  { label: 'EN loan 13', text: "the matcha latte with oat milk and a croissant is my favorite afternoon snack from the cafe", expectRomanized: false },
  { label: 'EN loan 14', text: "they celebrated with champagne and canapes at the soiree hosted by the ambassador at the embassy", expectRomanized: false },
  { label: 'EN loan 15', text: "the guru taught meditation techniques from ancient vedic traditions at the retreat center last weekend", expectRomanized: false },
  { label: 'EN loan 16', text: "she made an excellent dal with chapati and pickled mango achar for dinner last night it was great", expectRomanized: false },
  { label: 'EN loan 17', text: "the kimchi jjigae and bibimbap at the Korean restaurant were authentic and full of bold flavors", expectRomanized: false },
  { label: 'EN loan 18', text: "we visited the souk and bought some tagine spice mix za'atar and fresh baklava for dessert", expectRomanized: false },
  { label: 'EN loan 19', text: "the dim sum brunch included har gow siu mai char siu bao and egg tarts with jasmine tea", expectRomanized: false },
  { label: 'EN loan 20', text: "the tzatziki and dolmades at the taverna were perfect paired with grilled halloumi cheese and olives", expectRomanized: false },
  { label: 'EN loan 21', text: "she practices pilates and barre every morning before her commute for core strength and flexibility training", expectRomanized: false },
  { label: 'EN loan 22', text: "the pho and banh mi from the Vietnamese restaurant downtown are absolutely incredible best in the city", expectRomanized: false },
  { label: 'EN loan 23', text: "the samosa and pakora from the Indian takeaway were crispy and full of flavor with mint chutney", expectRomanized: false },
  { label: 'EN loan 24', text: "we celebrated the quinceañera with mariachi music piñatas and tres leches cake at the hall downtown", expectRomanized: false },
  { label: 'EN loan 25', text: "the bonsai exhibition at the botanical garden featured miniature maple juniper and pine tree specimens", expectRomanized: false },

  // ═══ Single-word tests (expectRomanized: false — too short) ═══
  { label: '1w namaste', text: "namaste", expectRomanized: false },
  { label: '1w salam', text: "salam", expectRomanized: false },
  { label: '1w konnichiwa', text: "konnichiwa", expectRomanized: false },
  { label: '1w annyeong', text: "annyeonghaseyo", expectRomanized: false },
  { label: '1w nihao', text: "nihao", expectRomanized: false },
  { label: '1w sawadee', text: "sawadee", expectRomanized: false },
  { label: '1w privet', text: "privet", expectRomanized: false },
  { label: '1w vanakkam', text: "vanakkam", expectRomanized: false },
  { label: '1w shukran', text: "shukran", expectRomanized: false },
  { label: '1w dhanyabaad', text: "dhanyabaad", expectRomanized: false },
  { label: '1w gamsahamnida', text: "gamsahamnida", expectRomanized: false },
  { label: '1w xiexie', text: "xiexie", expectRomanized: false },
  { label: '1w merci', text: "merci", expectRomanized: false },
  { label: '1w gracias', text: "gracias", expectRomanized: false },
  { label: '1w danke', text: "danke", expectRomanized: false },
  { label: '1w bhenchod', text: "bhenchod", expectRomanized: false },
  { label: '1w madarchod', text: "madarchod", expectRomanized: false },
  { label: '1w fuck', text: "fuck", expectRomanized: false },
  { label: '1w merde', text: "merde", expectRomanized: false },
  { label: '1w scheisse', text: "scheisse", expectRomanized: false },
  { label: '1w cazzo', text: "cazzo", expectRomanized: false },
  { label: '1w puta', text: "puta", expectRomanized: false },
  { label: '1w blyad', text: "blyad", expectRomanized: false },
  { label: '1w kuso', text: "kuso", expectRomanized: false },
  { label: '1w inshallah', text: "inshallah", expectRomanized: false },
  { label: '1w mashallah', text: "mashallah", expectRomanized: false },
  { label: '1w wallah', text: "wallah", expectRomanized: false },
  { label: '1w habibi', text: "habibi", expectRomanized: false },
  { label: '1w yalla', text: "yalla", expectRomanized: false },
  { label: '1w bonjour', text: "bonjour", expectRomanized: false },

  // ═══ Two-three word phrases (expectRomanized: false — too short) ═══
  { label: '2w namaste ji', text: "namaste ji", expectRomanized: false },
  { label: '2w salam alaikum', text: "salam alaikum", expectRomanized: false },
  { label: '2w arigatou gozaimasu', text: "arigatou gozaimasu", expectRomanized: false },
  { label: '2w ni hao', text: "ni hao ma", expectRomanized: false },
  { label: '2w kya haal', text: "kya haal hai", expectRomanized: false },
  { label: '2w kem cho', text: "kem cho", expectRomanized: false },
  { label: '2w como estas', text: "como estas amigo", expectRomanized: false },
  { label: '2w wie gehts', text: "wie gehts dir", expectRomanized: false },
  { label: '2w comment allez', text: "comment allez vous", expectRomanized: false },
  { label: '2w come stai', text: "come stai oggi", expectRomanized: false },
  { label: '2w sabai dee', text: "sabai dee mai", expectRomanized: false },
  { label: '2w tudo bem', text: "tudo bem amigo", expectRomanized: false },
  { label: '2w kak dela', text: "kak dela brat", expectRomanized: false },
  { label: '2w genki desu', text: "genki desu ka", expectRomanized: false },
  { label: '2w annyeong phrase', text: "annyeong haseyo", expectRomanized: false },
  { label: '2w merhaba nasil', text: "merhaba nasilsin", expectRomanized: false },
  { label: '2w apa kabar', text: "apa kabar teman", expectRomanized: false },
  { label: '2w habari yako', text: "habari yako rafiki", expectRomanized: false },
  { label: '2w kumusta ka', text: "kumusta ka na", expectRomanized: false },
  { label: '2w bom dia', text: "bom dia amigo", expectRomanized: false },

  // ═══ SMS/abbreviated text (expectRomanized: false) ═══
  { label: 'SMS en 1', text: "msg me l8r m8 im busy rn cant talk atm lol ttyl brb gonna grab food", expectRomanized: false },
  { label: 'SMS en 2', text: "omfg that was hilarious lmaoo i cant even rn dead af tbh no cap fr fr", expectRomanized: false },
  { label: 'SMS en 3', text: "wyd tonight we tryna go out hmu if ur down its gonna be lit fam no lie", expectRomanized: false },
  { label: 'SMS en 4', text: "ngl that test was easy af imo everyone who studied should pass ez clap gg no re", expectRomanized: false },
  { label: 'SMS fr 1', text: "slt ca va mdr trop drole lol jsui mort de rire ptdr tkl frere on se voit", expectRomanized: false },
  { label: 'SMS fr 2', text: "jpp de ce cours serieux c tro long mdr vivement les vacs on se casse vite", expectRomanized: false },
  { label: 'SMS fr 3', text: "rdv a 20h devant le cine dac pas de retard svp sinon on rate le debut merci", expectRomanized: false },
  { label: 'SMS es 1', text: "tio k pasa hace tpo k no te veo kdd manan vale bro no seas pesao venga", expectRomanized: false },
  { label: 'SMS es 2', text: "jajaja q risa me muero mazo gracioso tio no paro de reirme en serio jajajaja", expectRomanized: false },
  { label: 'SMS es 3', text: "ns k hacer hoy quedamos o q dime algo tio k me aburro en casa solo mazo", expectRomanized: false },
  { label: 'SMS de 1', text: "ey alter was geht komm raus lass was machen hab bock auf was lol gz", expectRomanized: false },
  { label: 'SMS de 2', text: "hdl hab dich lieb bis morgen cya gn8 schlaf gut traeume was schoenes hdgdl kuss", expectRomanized: false },
  { label: 'SMS pt 1', text: "eae mano blz td certo vlw flw tmj kkkk to de boa em casa hj fds top", expectRomanized: false },
  { label: 'SMS pt 2', text: "kkkk mto bom vc eh dms hahaha ri mt desse meme q vc mandou demais cara", expectRomanized: false },
  { label: 'SMS id 1', text: "gw lg males bgt hari ini mager banget pengen rebahan aja deh cape bgt kerja seharian", expectRomanized: false },
  { label: 'SMS id 2', text: "otw kesana bentar lg sampe jgn lupa bawa duit buat makan ye bro gas langsung", expectRomanized: false },
  { label: 'SMS tr 1', text: "nbr cok komik ya guldm baya mrb slm nb yarin gorusuruz bb ins tamam hadi", expectRomanized: false },
  { label: 'SMS tr 2', text: "tmm geliyorum birazdan dur orada bekle hemen cikyorum kapidan ustelik daha hizli olcam", expectRomanized: false },
  { label: 'SMS hi 1', text: "kya chal raha hai bro msg kar na kal milte h bye tc gn sd love u bhai", expectRomanized: false },
  { label: 'SMS hi 2', text: "acha ok thik hai kal baat krte hain abhi busy hu bhai sry ttyl cya phir milte h", expectRomanized: false },

  // ═══ Vietnamese with diacritics (expectRomanized: false — native orthography) ═══
  { label: 'VI diac 1', text: "Tôi rất vui được gặp bạn hôm nay thời tiết thật đẹp chúng ta đi chơi nhé", expectRomanized: false },
  { label: 'VI diac 2', text: "Xin chào bạn khỏe không hôm nay trời đẹp quá chúng ta đi dạo công viên nhé", expectRomanized: false },
  { label: 'VI diac 3', text: "Mẹ tôi nấu ăn rất ngon hôm nay cơm chiên và canh chua cá rất tuyệt vời", expectRomanized: false },
  { label: 'VI diac 4', text: "Trường đại học này có nhiều chương trình tốt cho sinh viên quốc tế từ khắp nơi", expectRomanized: false },
  { label: 'VI diac 5', text: "Hà Nội là thủ đô của Việt Nam có nhiều di tích lịch sử và văn hóa đặc sắc", expectRomanized: false },
  { label: 'VI diac 6', text: "Chúng tôi đi chợ mua rau củ quả thịt cá tươi và trái cây cho bữa cơm gia đình", expectRomanized: false },
  { label: 'VI diac 7', text: "Phở bò là món ăn truyền thống của Việt Nam nước dùng thơm ngon thịt bò mềm", expectRomanized: false },
  { label: 'VI diac 8', text: "Ngày mai tôi phải đi làm sớm nên hôm nay tôi đi ngủ sớm chúc ngủ ngon", expectRomanized: false },
  { label: 'VI diac 9', text: "Tết Nguyên Đán là ngày lễ lớn nhất của người Việt Nam cả gia đình sum họp", expectRomanized: false },
  { label: 'VI diac 10', text: "Thành phố Hồ Chí Minh rất nhộn nhịp có nhiều quán ăn ngon và chợ đêm sôi động", expectRomanized: false },
  { label: 'VI diac 11', text: "Cà phê sữa đá là thức uống yêu thích của nhiều người Việt Nam mỗi buổi sáng", expectRomanized: false },
  { label: 'VI diac 12', text: "Vịnh Hạ Long là di sản thế giới được UNESCO công nhận cảnh đẹp hùng vĩ tuyệt vời", expectRomanized: false },
  { label: 'VI diac 13', text: "Bánh mì Việt Nam nổi tiếng thế giới với nhân thịt rau sống và nước sốt đặc biệt", expectRomanized: false },
  { label: 'VI diac 14', text: "Chợ Bến Thành là điểm du lịch nổi tiếng ở Sài Gòn bán đủ thứ mọi người đều thích", expectRomanized: false },
  { label: 'VI diac 15', text: "Áo dài là trang phục truyền thống của phụ nữ Việt Nam rất đẹp và thanh lịch", expectRomanized: false },

  // ═══ Long stress tests — romanized (expectRomanized: true) ═══
  { label: 'HI long stress 1', text: "aaj hamare mohalle mein ek bahut bada mela laga hua hai jahan bahut saare log aaye hain apne parivaar ke saath bachchon ke liye jhule hain aur khane pine ke bahut saare stall lage hain mausam bhi bahut achha hai aaj toh sabko bahut maza aa raha hai shaam ko ek sangeet karyakram bhi hoga jismein bahut achhe gaayak gaana gaayenge hum sab bahut excited hain is mele ke liye bahut din se intezaar kar rahe the sach mein bahut badhiya hai sab kuch aaj", expectRomanized: true },
  { label: 'HI long stress 2', text: "mere chacha ji ka ghar bahut bada hai unke yahan ek bahut sundar bagicha hai jismein tarah tarah ke phool khilte hain gulaab chameli aur mogra ke phool ki khushboo se poora ghar mahakta rehta hai bachche wahan khelne jaate hain aur ghar ke buzurg shaam ko baithkar chai peete hain aur purani yaadein taaza karte hain yeh sab dekhkar bahut achha lagta hai dil ko sukoon milta hai sachchi baat hai yeh", expectRomanized: true },
  { label: 'HI long stress 3', text: "kal hamare school mein annual function hua tha jismein bahut saare bachchon ne dance kiya gaana gaaya aur natak bhi pesh kiya hamari principal ne sabko badhai di aur kaha ki sab bachchon ne bahut mehnat ki hai unhe garv hai sabhi par maa papa bhi aaye the sabhi bahut khush the function ke baad sabne saath mein khana khaya aur photo bhi khichwaaye bahut yaadgaar din tha sach mein", expectRomanized: true },
  { label: 'AR long stress 1', text: "ana rayeh lal souk alyom ashteri khudra wa fakha la ummi al jaw helw ktir al youm wa ana mashallah bikhair ba3dein baddi rouh la beit sadeeqi la nitsalla sawa wa nitkallam shway inshallah bukra mnitruk la al bahr ma3 al shabab killon mwafeqin wa mabsouteen ktir wallah al hayat helweh lamma itkoun ma3 il ahbab wil asdiqa2 allah yis3id il jami3 ya rab inshallah nsalli sawa walla killon mnib3as", expectRomanized: true },
  { label: 'AR long stress 2', text: "kul youm bisir 3inna shi jdid bil madraseh il oustaz byifham 3aleina ktir wa bi3allimna b tari2a helweh il mawad sa3beh shway bas ma3 il dars wil jihad kul shi bisir sahel il tullab il tanyeen mnih ktir wa killon bi sa3dou ba3ad inshallah ni njah bi imtihanat akhir il sineh bi 3alamat 3alyeh killon yistahil in najah wallah il draseh muhimmeh ktir", expectRomanized: true },
  { label: 'RU long stress 1', text: "segodnya my s druzyami poshli v park gulyat potomu chto pogoda byla ochen khoroshaya my vziali s soboi edu i napitki i ustroili piknik na trave potom my igrali v futbol i khorosho proveli vremya vecherom my poshli domoi ustavshiye no schastliviye ot zamechatelnogo dnya babushka gotovila nam vkusnyi uzhin a dedushka rasskazal interesniye istorii iz svoey molodosti vsem bylo ochen veselo i teplo na dushe", expectRomanized: true },
  { label: 'RU long stress 2', text: "moya lyubimaya pora goda eto osen kogda listya menyayut svoy tsvet na krasnyy zholtyy i oranzhevyy pogoda stanovitsya prokhlodnoy no ne kholodnoy ya lyublyu gulyat po parku i soburat opadshiye listya deti raduyutsya kazhdomu dnu i begayut po luzham v rezinovykh sapogakh mama pechot pirogi s yablokami a papa razzhigaet kamin vecher prosto volshebnyy osen eto magiya prirody kotoraya nikogda ne nadoedaet mne", expectRomanized: true },
  { label: 'RU long stress 3', text: "v proshlom godu myezdili v Sankt Peterburg i posetili mnogo znamenitykh mest my videli Ermitazh Petergof Isaakievskiy sobor i guyali po Nevskomy prospektu gorod ochen krasivyy osobenno letom kogda belye nochi ya khotel by vernutsya tuda snova potomu chto ne uspel posmotret vsyo chto khotel eto byl odin iz luchshikh otpuskov v moyey zhizni spasibo druzbyam za kompaniyu", expectRomanized: true },
  { label: 'JA long stress 1', text: "kyou watashi wa tomodachi to issho ni kouen ni ikimashita tenki ga totemo yokatta desu kara sampo shite bento o tabemashita sorekara kouen no naka de shashin o torimashita yoru ni natte kara resutoran de bangohan o tabemashita totemo tanoshii ichinichi deshita mata raishu mo ikitai desu tomodachi to issho ni sugoshita jikan wa totemo takaramono desu sorezore no omoide ga kokoro ni nokotte imasu hontou ni subarashii ichinichi deshita", expectRomanized: true },
  { label: 'ZH long stress 1', text: "jintian wo he pengyoumen yiqi qu le gongyuan tianqi hen hao suoyi women sanbu le hen chang shijian ranhou women zai caodi shang chi le wufan xiawu women pai le hen duo zhaopian wanshang women qu le yijia canting chi wanfan jintian zhen shi kuaile de yitian wo xiwang xiaci hai keyi qu wo juede he pengyou yiqi wan shi zui kuaile de shi qing meici chulai wan dou hen kaixin xiwang yihou hai you jihui", expectRomanized: true },
  { label: 'KO long stress 1', text: "oneul chingudeul gwa gachi gongwon e gasseoyo nalssiga joeoseo sancheck hago dosirak eul meogeo sseoyo geurigo gongwon eseo sajin eul jjigeosseoyo jeonyeoge reseuteorang eseo jeonyeog eul meogeosseoyo jeongmal jaemiissneun haru yeosseoyo daeume tto gago sipeoyo gamsahamnida chingu deul gwa hamkke haneun sigani gajang haengbokhamnida uri jeongmal joheun chingu deul imnida maeil gachi mannago sipeoyo", expectRomanized: true },

  // ═══ Romanized profanity (expectRomanized: true) ═══
  { label: 'HI prof rom 1', text: "bhenchod madarchod saala kutta kamina harami gaandu chutiya haram zaada", expectRomanized: true },
  { label: 'HI prof rom 2', text: "teri maa ki gaali deta hoon saale haramkhor kameene bhosdi ke kutte", expectRomanized: true },
  { label: 'HI prof rom 3', text: "saala gadha hai yeh aadmi bahut bada bewakoof hai kamina harami kutta", expectRomanized: true },
  { label: 'AR prof rom 1', text: "ibn il sharmouta ya kalb ya hmar kos ummak ahbal ya zalameh wallah", expectRomanized: true },
  { label: 'AR prof rom 2', text: "ya ibn il sharmouta kos ummak ya haiwan ya kalb sharmout wallah ahbal", expectRomanized: true },
  { label: 'RU prof rom 1', text: "blyad suka nahui pizdets ebanyi mudak der mo zhopa davai poshol nahui", expectRomanized: true },
  { label: 'RU prof rom 2', text: "idi nahui suka blyad pizdets kakoy mudak ebanyi vrot ti gavno polnoye", expectRomanized: true },
  { label: 'ZH prof rom 1', text: "cao ni ma sha bi wang ba dan tamade gundan bichi ta ma de zhongguo", expectRomanized: true },
  { label: 'ZH prof rom 2', text: "ni shi sha bi cao ni ma de tamade hun dan wang ba dan zhu tou", expectRomanized: true },
  { label: 'KO prof rom 1', text: "shibal gaesaekki jiral ssibalnoma jenjang babo michinnon meongcheong ssibal", expectRomanized: true },
  { label: 'KO prof rom 2', text: "ssibal gaesaekki neo michyeosseo jenjang babo meongcheonghan noma shibal", expectRomanized: true },
  { label: 'JA prof rom 1', text: "kuso yarou baka shine temee fuzakenuna kichiku kisama bakayarou aho desu", expectRomanized: true },
  { label: 'UR prof rom 1', text: "harami kutta bhenchod gaandu saala kamina haram zaada badtameez kameena", expectRomanized: true },
  { label: 'FA prof rom 1', text: "koskesh madar jendeh pedar sag khar kos naneh kiri haramzadeh bache koni", expectRomanized: true },
  { label: 'BN prof rom 1', text: "chagol shala khanki magi sala harami banchod chodu magi baler baccha shaala", expectRomanized: true },
];
