export const romanizedCases: { label: string; text: string; expectRomanized: boolean }[] = [
  // ═══ Hindi romanized ═══
  { label: 'HI rom 1', text: "mujhe bahut garmi lag rahi hai bahar mat jao abhi", expectRomanized: true },
  { label: 'HI rom 2', text: "meri maa ne achha khana banaya hai aaj raat ke liye", expectRomanized: true },
  { label: 'HI rom 3', text: "kal school mein bahut maza aaya tha dost ke saath khele", expectRomanized: true },
  { label: 'HI rom 4', text: "yaar mujhe bahut neend aa rahi hai main so jaata hoon", expectRomanized: true },
  { label: 'HI rom 5', text: "bazaar se sabzi lani hai aur thoda doodh bhi lana hai ghar ke liye", expectRomanized: true },
  { label: 'HI rom 6', text: "diwali pe ghar ko bahut achhe se sajaya tha sabne bahut tareef ki", expectRomanized: true },
  { label: 'HI rom 7', text: "papa ne nayi gaadi kharidi hai bahut khush hain sab ghar mein", expectRomanized: true },
  { label: 'HI rom 8', text: "mere bhai ki shaadi hai agale mahine bahut taiyari karni hai", expectRomanized: true },
  { label: 'HI rom 9', text: "aaj cricket match dekha india ne bahut achha khela bahut maza aaya", expectRomanized: true },
  { label: 'HI rom 10', text: "doctor ne kaha ki dawai samay pe khana zaruri hai theek hone ke liye", expectRomanized: true },
  { label: 'HI rom 11', text: "rishton mein pyaar bahut zaroori hai bina pyaar ke kuch nahi hota", expectRomanized: true },
  { label: 'HI rom 12', text: "train bahut late aa rahi hai station pe bahut bheed hai aaj", expectRomanized: true },
  { label: 'HI rom 13', text: "ghar pe wifi nahi chal raha hai bahut pareshani ho rahi hai", expectRomanized: true },
  { label: 'HI rom 14', text: "aaj bahut thand hai sweater pehan ke jaana mat bhoolo bahar", expectRomanized: true },
  { label: 'HI rom 15', text: "mere dost ne mujhe ek bahut achhi kitab di padhne ke liye", expectRomanized: true },
  { label: 'HI rom 16', text: "holi pe hum sab rang khelte hain aur mithai khaate hain bahut maza", expectRomanized: true },
  { label: 'HI rom 17', text: "parso hamare ghar pe mehman aa rahe hain taiyari karni padegi", expectRomanized: true },
  { label: 'HI rom 18', text: "subah jaldi uthna chahiye sehat ke liye bahut achha hota hai", expectRomanized: true },
  { label: 'HI rom 19', text: "biryani bahut tasty bani hai aaj maa ne kamaal kar diya sach mein", expectRomanized: true },
  { label: 'HI rom 20', text: "exam ki taiyari mein bahut busy hoon kuch din baad milte hain", expectRomanized: true },
  { label: 'HI rom 21', text: "sapne mein aaj kuch ajeeb dekha bahut dar gaya tha raat ko", expectRomanized: true },
  { label: 'HI rom 22', text: "bachpan mein hum sab galli mein khelne jaate the roz shaam ko", expectRomanized: true },
  { label: 'HI rom 23', text: "aaj mandir mein pooja ki bahut achha laga mann shant ho gaya", expectRomanized: true },
  { label: 'HI rom 24', text: "nani ke ghar jaana hai garmiyon ki chhutti mein bahut maza aayega", expectRomanized: true },
  { label: 'HI rom 25', text: "barish mein bheeg gaye kapde badalne padenge ghar jake turant", expectRomanized: true },
  { label: 'HI rom 26', text: "chai peete hue baat karte hain kitna achha lagta hai shaam ko", expectRomanized: true },
  { label: 'HI rom 27', text: "rickshaw wale ne zyada paisa maanga bahut bura lagta hai yaar", expectRomanized: true },
  { label: 'HI rom 28', text: "aaj pehli baar pahad dekhe bahut khubsurat nazara tha wakai mein", expectRomanized: true },
  { label: 'HI rom 29', text: "roti sabzi daal chawal yeh hamara roz ka khana hai ghar mein", expectRomanized: true },
  { label: 'HI rom 30', text: "gaon mein abhi bhi bijli ki bahut samasya hai roz aati jaati hai", expectRomanized: true },
  { label: 'HI rom 31', text: "shaadi mein bahut nachna hota hai aur khana bhi bahut achha milta hai", expectRomanized: true },
  { label: 'HI rom 32', text: "mere padosi bahut achhe hain hamesha madad karte hain zaroorat mein", expectRomanized: true },
  { label: 'HI rom 33', text: "ladki bahut samajhdar hai padhai mein bhi achhi hai aur kaam mein bhi", expectRomanized: true },
  { label: 'HI rom 34', text: "aaj raat ko bahut taare dikh rahe hain aasmaan bahut saaf hai", expectRomanized: true },
  { label: 'HI rom 35', text: "pani pi lo bahut garmi hai dehydration ho jayega nahi toh dhyan rakho", expectRomanized: true },
  { label: 'HI rom 36', text: "bhaiya mujhe thoda paisa chahiye kitab khareedni hai padhai ke liye", expectRomanized: true },
  { label: 'HI rom 37', text: "samosa aur jalebi khaane ka mann kar raha hai chalo bazaar chalte hain", expectRomanized: true },
  { label: 'HI rom 38', text: "maa kehti hai ki mehnati aadmi hamesha safal hota hai zindagi mein", expectRomanized: true },
  { label: 'HI rom 39', text: "uske saath bahut achha waqt guzra yaadein hamesha rahegi mere paas", expectRomanized: true },
  { label: 'HI rom 40', text: "dusron ki madad karo toh khushi milti hai bahut achha lagta hai dil ko", expectRomanized: true },
  { label: 'HI rom 41', text: "ghar ki safai karni hai bahut gandagi ho gayi hai har jagah dhool hai", expectRomanized: true },
  { label: 'HI rom 42', text: "kal hamne bahut mazedaar picnic ki thi jungle mein sab ne enjoy kiya", expectRomanized: true },
  { label: 'HI rom 43', text: "budhe log kehte hain ki zamana bahut badal gaya hai pehle aisa nahi tha", expectRomanized: true },
  { label: 'HI rom 44', text: "chhoti behen bahut shaitan hai din bhar shararat karti rehti hai", expectRomanized: true },
  { label: 'HI rom 45', text: "kisan bahut mehnat karta hai khet mein subah se shaam tak kaam karta", expectRomanized: true },

  // ═══ Urdu romanized ═══
  { label: 'UR rom 1', text: "aaj bazaar jaana hai kuch cheezein leni hain ghar ke liye zaruri hain", expectRomanized: true },
  { label: 'UR rom 2', text: "ramzan ka mahina bahut pyara hota hai roza rakhte hain sab log", expectRomanized: true },
  { label: 'UR rom 3', text: "ammi ne bahut achha pulao banaya hai aaj sab ko bulaya hai khaane pe", expectRomanized: true },
  { label: 'UR rom 4', text: "eid pe naye kapde pehente hain aur sewaiyaan khaate hain bahut khushi hoti", expectRomanized: true },
  { label: 'UR rom 5', text: "abbu ne mujhe nayi cycle di hai bahut khush hoon main aaj kal", expectRomanized: true },
  { label: 'UR rom 6', text: "masjid mein namaz padhne jaate hain roz subah aur shaam ko bhi", expectRomanized: true },
  { label: 'UR rom 7', text: "lahore mein khaana bahut lajawab hota hai nihari paye haleem sab milta hai", expectRomanized: true },
  { label: 'UR rom 8', text: "bhai jaan aap se ek guzarish hai meri baat sun lein zara", expectRomanized: true },
  { label: 'UR rom 9', text: "shadi mein dulha dulhan bahut khubsurat lag rahe the mashallah kya nazara tha", expectRomanized: true },
  { label: 'UR rom 10', text: "cricket match mein pakistan ne bahut achha khela sab khush hain aaj", expectRomanized: true },
  { label: 'UR rom 11', text: "dawa khana mat bhoolo warna tabiyat phir se kharab ho jayegi tumhari", expectRomanized: true },
  { label: 'UR rom 12', text: "mere chacha karachi mein rehte hain unke ghar jaana hai agley hafte", expectRomanized: true },
  { label: 'UR rom 13', text: "garam chai peeyo thand bahut hai aur baarish bhi ho rahi hai bahar", expectRomanized: true },
  { label: 'UR rom 14', text: "mehnat karo allah tumhari madad karega hamesha sacchi baat hai yeh", expectRomanized: true },
  { label: 'UR rom 15', text: "quran shareef ki tilawat karo roz subah bahut barkat aati hai ghar mein", expectRomanized: true },
  { label: 'UR rom 16', text: "bachon ko parhaao yeh tumhara farz hai unka mustaqbil tumhare haath mein hai", expectRomanized: true },
  { label: 'UR rom 17', text: "biryani ke saath raita aur salad bhi lagao bahut mazedaar lagta hai", expectRomanized: true },
  { label: 'UR rom 18', text: "khuda hafiz dost apna khayal rakhna hamesha duaon mein yaad rakhna", expectRomanized: true },
  { label: 'UR rom 19', text: "mushaira mein bahut achhi shayari suni kal raat ko dil khush ho gaya", expectRomanized: true },
  { label: 'UR rom 20', text: "peshawar ki chapli kebab duniya mein mashoor hai sab ko pasand aati hai", expectRomanized: true },
  { label: 'UR rom 21', text: "ustaad sahab ne hamein achhi taalim di hai unka ehsaan kabhi nahi bhoolunga", expectRomanized: true },
  { label: 'UR rom 22', text: "lassi peeyo garmi mein bahut faida hota hai sehat ke liye achhi hai", expectRomanized: true },
  { label: 'UR rom 23', text: "gaon mein zindagi bahut sakoon wali hai sheher ki bheed nahi hoti wahan", expectRomanized: true },
  { label: 'UR rom 24', text: "chand raat pe mehndi lagaate hain aur eid ki taiyari karte hain sab", expectRomanized: true },
  { label: 'UR rom 25', text: "dost ke saath waqt guzaarna bahut achha lagta hai dil khush hota hai", expectRomanized: true },

  // ═══ Arabic romanized ═══
  { label: 'AR rom 1', text: "ana rayeh lal souq ashteri khudra wa fakha la beit alyom", expectRomanized: true },
  { label: 'AR rom 2', text: "keef halak ya akhi shu akhbarak alyom inshallah bikhair", expectRomanized: true },
  { label: 'AR rom 3', text: "wallah ana mish fahim shu bidak tihki ya zalameh khalas", expectRomanized: true },
  { label: 'AR rom 4', text: "hayati ana bahebik ktir inti ahla wahdeh bil dunya kullha", expectRomanized: true },
  { label: 'AR rom 5', text: "yalla nrouh lal bahar bukra el jaw helw ktir mashallah", expectRomanized: true },
  { label: 'AR rom 6', text: "mama tabakhet maqlubeh alyom rihet il akl killon jow3anin", expectRomanized: true },
  { label: 'AR rom 7', text: "ramadan kareem kil 3ayleh nsoom wa niftar sawa inshallah", expectRomanized: true },
  { label: 'AR rom 8', text: "3id mubarak la kil il nas inshallah tkoun sanih sa3ideh", expectRomanized: true },
  { label: 'AR rom 9', text: "bukra 3indi imtihan lazim udrus il layleh kullha ya rab sa3idni", expectRomanized: true },
  { label: 'AR rom 10', text: "ahla shi bil hayat lamma il ahal yijtam3ou sawa 3al akil", expectRomanized: true },
  { label: 'AR rom 11', text: "el lahmeh mashwiyeh 3al fahem ahla shi momkin toklha ya zalameh", expectRomanized: true },
  { label: 'AR rom 12', text: "ana min souriyya bas 3ayish bil khaleej halla2 shughul", expectRomanized: true },
  { label: 'AR rom 13', text: "sahrit il bariheh kanat hilweh ktir 2a3adna nihki w nid7ak", expectRomanized: true },
  { label: 'AR rom 14', text: "tisbah 3ala khair ya sadeeqi noum il 3afyeh bukra niltaqi", expectRomanized: true },
  { label: 'AR rom 15', text: "il 3aris wil 3arouseh kano hilwin mashallah allah yis3idhom", expectRomanized: true },
  { label: 'AR rom 16', text: "shukran jazilan 3ala il hadiyeh hilweh ktir habbaytha wallah", expectRomanized: true },
  { label: 'AR rom 17', text: "il walad shater bil madraseh dayman awwal 3ala saffou mashallah", expectRomanized: true },
  { label: 'AR rom 18', text: "khalas ta3abt min il shughul baddi irta7 shway bil beit alyom", expectRomanized: true },
  { label: 'AR rom 19', text: "jiddeh helweh ktir fi ashya2 ktir titsawwa2 feeha bil leil", expectRomanized: true },
  { label: 'AR rom 20', text: "lamma btimzah ma3i ana btiz3al ktir la tihki hek ma3i ba3dein", expectRomanized: true },
  { label: 'AR rom 21', text: "il jaw 7ar ktir alyom mish 2ader utla3 min il beit abadan", expectRomanized: true },
  { label: 'AR rom 22', text: "baba ishtara sayyara jdeedeh mbari7 kullna fir7anin ktir wallah", expectRomanized: true },
  { label: 'AR rom 23', text: "ya rab i7faz ahli wa as7abi min kull shar ya kareem", expectRomanized: true },
  { label: 'AR rom 24', text: "kunafeh nablusiyyeh atiyab 7ilwiyyat bil 3alam killon bi7ibbuha", expectRomanized: true },
  { label: 'AR rom 25', text: "il jami3a sa3beh bas lazim nikmal ta3limna 3ashan il mustaqbal", expectRomanized: true },

  // ═══ Russian romanized ═══
  { label: 'RU rom 1', text: "mne nado kupit produkty v magazine segodnya vecherom posle raboty", expectRomanized: true },
  { label: 'RU rom 2', text: "zavtra u nas ekzamen nado gotovitsya vsyu noch na kuhne", expectRomanized: true },
  { label: 'RU rom 3', text: "pogoda segodnya prosto zamechatelnaya mozhno poyti gulyat v park", expectRomanized: true },
  { label: 'RU rom 4', text: "ya ochen lyublyu russkuyu kuhnyu borshch pelmeni i bliny moi lyubimye", expectRomanized: true },
  { label: 'RU rom 5', text: "mama prigotovila ochen vkusnyi uzhin segodnya vsya semya sobralas", expectRomanized: true },
  { label: 'RU rom 6', text: "moi druzya priglasili menya na den rozhdeniya v subbotu vecherom", expectRomanized: true },
  { label: 'RU rom 7', text: "v moskve seychas ochen kholodno nado odevatsya teplo kazhdyi den", expectRomanized: true },
  { label: 'RU rom 8', text: "ya chitayu ochen interesnuyu knigu pro istoriyu rossii seychas", expectRomanized: true },
  { label: 'RU rom 9', text: "nash kot ochen smeshnoi on vsegda igraet s myachikom po kvartire", expectRomanized: true },
  { label: 'RU rom 10', text: "letom my poedim na more v krym tam ochen krasivo vsegda", expectRomanized: true },
  { label: 'RU rom 11', text: "babushka gotovit samye vkusnye pirogi s myasom i kartoshkoi doma", expectRomanized: true },
  { label: 'RU rom 12', text: "v universitete segodnya byli ochen interesnye lektsii po fizike", expectRomanized: true },
  { label: 'RU rom 13', text: "davai vstretimtsya v kafe zavtra utrom i popyom kofe vmeste", expectRomanized: true },
  { label: 'RU rom 14', text: "ya smotrel ochen khoroshiy film vchera vecher om pro voynu", expectRomanized: true },
  { label: 'RU rom 15', text: "na novyi god my vsegda sobiraemtsya vsej semyoj i prazdnuem", expectRomanized: true },
  { label: 'RU rom 16', text: "mne ochen nravitsya musyka tchaikovskogo osobenno lebedinoe ozero", expectRomanized: true },
  { label: 'RU rom 17', text: "detstvo bylo zamechatelnym vremenem my igrali vo dvore kazhdyi den", expectRomanized: true },
  { label: 'RU rom 18', text: "spasibo bolshoye za vashu pomoshch mne eto ochen vazhno seychas", expectRomanized: true },
  { label: 'RU rom 19', text: "ya khochu nauchitsya gotovit borshch kak moya babushka delala ranshe", expectRomanized: true },
  { label: 'RU rom 20', text: "pozhaluysta peredayte sol i perets mne nuzhno dlya salata syuda", expectRomanized: true },
  { label: 'RU rom 21', text: "zavtra rano vstavat nado lech spat poranshe segodnya nochyu", expectRomanized: true },
  { label: 'RU rom 22', text: "metro v peterburge ochen krasivoe stantsii kak muzei vyglyadyat", expectRomanized: true },
  { label: 'RU rom 23', text: "moya sestra uchitsya v medicinskom institute ona hochet stat vrachom", expectRomanized: true },
  { label: 'RU rom 24', text: "na ulice segodnya ochen vetrano i kholodno luchshe ostavatsya doma", expectRomanized: true },
  { label: 'RU rom 25', text: "rossiyskiy futbol stanovitsya luchshe kazhdyi god ya smotru vse matchi", expectRomanized: true },

  // ═══ Japanese romaji ═══
  { label: 'JA rom 1', text: "ashita tomodachi to eiga o mi ni ikimasu tanoshimi desu", expectRomanized: true },
  { label: 'JA rom 2', text: "kono resutoran no ramen wa totemo oishii desu yo tabete mite", expectRomanized: true },
  { label: 'JA rom 3', text: "nihongo no benkyou wa muzukashii desu ga omoshiroi desu ne", expectRomanized: true },
  { label: 'JA rom 4', text: "kyou no tenki wa totemo ii desu ne sampo ni ikimashou ka", expectRomanized: true },
  { label: 'JA rom 5', text: "sumimasen kono densha wa tokyo eki ni ikimasu ka oshiete kudasai", expectRomanized: true },
  { label: 'JA rom 6', text: "watashi no kazoku wa yonin desu chichi haha ani to watashi", expectRomanized: true },
  { label: 'JA rom 7', text: "nihon no sakura wa haru ni totemo kirei desu hanami ga suki", expectRomanized: true },
  { label: 'JA rom 8', text: "kinou no pati wa totemo tanoshikatta minna de odorimashita", expectRomanized: true },
  { label: 'JA rom 9', text: "sushi to sashimi ga daisuki desu mainichi tabetai desu ne", expectRomanized: true },
  { label: 'JA rom 10', text: "gakkou de atarashii sensei ga kimashita totemo yasashii hito desu", expectRomanized: true },
  { label: 'JA rom 11', text: "natsuyasumi ni okinawa ni ikitai desu umi ga totemo kirei", expectRomanized: true },
  { label: 'JA rom 12', text: "kono hon wa totemo omoshirokatta isshuukan de yomimashita zenbu", expectRomanized: true },
  { label: 'JA rom 13', text: "maiasa shichiji ni okimasu soshite asa gohan o tabemasu itsumo", expectRomanized: true },
  { label: 'JA rom 14', text: "densha no naka de manga o yomu no ga suki desu mainichi", expectRomanized: true },
  { label: 'JA rom 15', text: "rainen nihon ni ryugaku shitai desu ima okane o tamete imasu", expectRomanized: true },
  { label: 'JA rom 16', text: "tomodachi ga byouki desu kara omimai ni ikimasu ashita gogo", expectRomanized: true },
  { label: 'JA rom 17', text: "fuji san ni noborimashita totemo tsukaremashita demo kirei deshita", expectRomanized: true },
  { label: 'JA rom 18', text: "nihon no natsu wa totemo atsui desu kara eakon ga hitsuyou desu", expectRomanized: true },
  { label: 'JA rom 19', text: "karaoke ni ikimashou minna de utaimashou tanoshii desu yo kitto", expectRomanized: true },
  { label: 'JA rom 20', text: "obento o tsukurimashita onigiri to tamagoyaki to yakizakana desu", expectRomanized: true },
  { label: 'JA rom 21', text: "shinkansen de osaka made ikimashita san jikan gurai kakarimashita", expectRomanized: true },
  { label: 'JA rom 22', text: "konbanwa kyou no shigoto wa taihen deshita tsukaremashita totemo", expectRomanized: true },
  { label: 'JA rom 23', text: "matsuri de takoyaki to yakisoba o tabemashita totemo oishikatta", expectRomanized: true },
  { label: 'JA rom 24', text: "nihon no onsen wa saikou desu tsukareta karada ga naorimasuu", expectRomanized: true },
  { label: 'JA rom 25', text: "watashi wa mainichi nihongo o renshuu shite imasu jouzu ni naritai", expectRomanized: true },

  // ═══ Korean romanized ═══
  { label: 'KO rom 1', text: "oneul achim bap meogeosseoyo jinjja masisseosseoyo gamsahamnida", expectRomanized: true },
  { label: 'KO rom 2', text: "uri gachi yeonghwa boreo galkka yo jaemiisseul geoya jinjja", expectRomanized: true },
  { label: 'KO rom 3', text: "hangugeo gongbu haneun geot joeyo maeil yeonseup hago isseoyo", expectRomanized: true },
  { label: 'KO rom 4', text: "oneul nalssiga joeyo sancheck halkka yo gachi gayo uri", expectRomanized: true },
  { label: 'KO rom 5', text: "annyeonghaseyo mannaseo bangapseumnida jeoneun hangugin imnida", expectRomanized: true },
  { label: 'KO rom 6', text: "ibeon jumale busan e yeoheng galkka hago isseoyo jal morugeosseoyo", expectRomanized: true },
  { label: 'KO rom 7', text: "kimchi jjigae jom mandeulkkayo oneul jeonyeoge meokkeo sipeoyo", expectRomanized: true },
  { label: 'KO rom 8', text: "hakkyo eseo siheum bwasseoyo jom eoryeowosseoyo geundae gwaenchanayo", expectRomanized: true },
  { label: 'KO rom 9', text: "saranghaeyo dangsin eun nae insaeng eseo gajang jungyohan saram", expectRomanized: true },
  { label: 'KO rom 10', text: "ppali ppali haeya dwaeyo sigani eopseoyo neujeul geot gatayo", expectRomanized: true },
  { label: 'KO rom 11', text: "seoul eseo busan kkaji ktx ro du sigan geollimyeon dwaeyo", expectRomanized: true },
  { label: 'KO rom 12', text: "noraebang galkka yo norae bureulkka gachi jaemissge bolkka yo", expectRomanized: true },
  { label: 'KO rom 13', text: "chuseok e gajok deul gwa hamkke songpyeon mandeuleoyo jeontong", expectRomanized: true },
  { label: 'KO rom 14', text: "oneul hoesa eseo hoeui isseoyo jom neujeul geot gatayo joesongamnida", expectRomanized: true },
  { label: 'KO rom 15', text: "tteokbokki rang sundae meokgo sipeoyo uri gachi gayo ppalli", expectRomanized: true },
  { label: 'KO rom 16', text: "bangapsumnida oraenmaninde eotteoke jinaeseyo geongang haseyo", expectRomanized: true },
  { label: 'KO rom 17', text: "daehanminguk mansei uri nara daepyo tim eul eungwon hamnida", expectRomanized: true },
  { label: 'KO rom 18', text: "naeil achim ilccik ireona ya haeyo junbi hal geosi maneyo", expectRomanized: true },
  { label: 'KO rom 19', text: "maekju hanjan halkka yo toyo il e chingu deul gwa gachi", expectRomanized: true },
  { label: 'KO rom 20', text: "jeju do e gago sipeoyo bada ga neomu yeppeoyo gamsahamnida", expectRomanized: true },

  // ═══ Chinese Pinyin ═══
  { label: 'ZH pin 1', text: "jintian wanshang women yiqi qu kan dianying hao bu hao", expectRomanized: true },
  { label: 'ZH pin 2', text: "zhe jia canting de cai hen haochi ni xihuan ma pengyou", expectRomanized: true },
  { label: 'ZH pin 3', text: "wo zuijin hen mang meitian dou yao jiaban dao hen wan cai huijia", expectRomanized: true },
  { label: 'ZH pin 4', text: "mingtian shi xingqiliu women keyi qu gongyuan wan yiqi ba", expectRomanized: true },
  { label: 'ZH pin 5', text: "zhongguo de lishi hen youyisi wo zai xuexi zhongwen xianzai", expectRomanized: true },
  { label: 'ZH pin 6', text: "xiexie ni de bangzhu wo zhen de hen ganxie ni pengyou", expectRomanized: true },
  { label: 'ZH pin 7', text: "beijing de tianqi zuijin hen leng yao duo chuan yidian yifu", expectRomanized: true },
  { label: 'ZH pin 8', text: "wo mama zuo de hongshaorou shi zuihao chi de cai zhen xiang", expectRomanized: true },
  { label: 'ZH pin 9', text: "didi he meimei dou zai xuexiao shangke baba mama zai gongsi gongzuo", expectRomanized: true },
  { label: 'ZH pin 10', text: "chunjie shi zhongguo zui zhongyao de jieri quanjia tuanyuan yiqi", expectRomanized: true },
  { label: 'ZH pin 11', text: "wo xiang xue zuofan keyi jiao wo ma wo xihuan zhongguo cai", expectRomanized: true },
  { label: 'ZH pin 12', text: "zuotian wanshang wo he pengyou yiqi qu le karaoke chang ge hen haowan", expectRomanized: true },
  { label: 'ZH pin 13', text: "shanghai shi yige hen da de chengshi renkou feichang duo ye hen remao", expectRomanized: true },
  { label: 'ZH pin 14', text: "wo de zhongwen laoshi hen you naixin jiao de ye hen hao zhen bang", expectRomanized: true },
  { label: 'ZH pin 15', text: "xia ge yue wo yao qu zhongguo luyou feichang qidai zhe ci luxing", expectRomanized: true },
  { label: 'ZH pin 16', text: "gongfu cha hen haohe wo meitian dou yao he ji bei gang qi lai", expectRomanized: true },
  { label: 'ZH pin 17', text: "nimen hao huanying lai women de xuexiao qing jin lai zuozuo", expectRomanized: true },
  { label: 'ZH pin 18', text: "wo juede yundong dui shenti hen hao meitian pao bu ban xiaoshi", expectRomanized: true },
  { label: 'ZH pin 19', text: "zhege zhoumo tianqi hao de hua women qu pasan zenmeyang", expectRomanized: true },
  { label: 'ZH pin 20', text: "duibuqi wo chidao le yinwei ditie chu le wenti hen baoqian", expectRomanized: true },

  // ═══ Bengali romanized ═══
  { label: 'BN rom 1', text: "amar bari dhaka te ami prai roj school jai bhai ki korcho", expectRomanized: true },
  { label: 'BN rom 2', text: "aaj brishti hobe bole mone hocche chata niye jao baire gele", expectRomanized: true },
  { label: 'BN rom 3', text: "maa bahut bhalo ranna kore aaj machher jhol diye bhat khabo", expectRomanized: true },
  { label: 'BN rom 4', text: "durga pujo te amra shobai mile pujor pandal ghuri dekhte jai", expectRomanized: true },
  { label: 'BN rom 5', text: "kolkata te rosogolla bahut mishti aur bhalo lagche khabar ki bolo", expectRomanized: true },
  { label: 'BN rom 6', text: "ami tomake onek bhalobashi tumi amar jibone shob cheye guruttopurno", expectRomanized: true },
  { label: 'BN rom 7', text: "baba office theke phire eshche aaj onek kaj chhilo bole khub klanto", expectRomanized: true },
  { label: 'BN rom 8', text: "tumi ki kal amader barite ashbe dada boudi shobai tomar jonno opekkha korche", expectRomanized: true },
  { label: 'BN rom 9', text: "ami gaan gaite onek bhalo bashi rabindra sangeet amar priya", expectRomanized: true },
  { label: 'BN rom 10', text: "sundarbaner bagh bahut sundar kintu bhoyonkor shob desher garbo", expectRomanized: true },
  { label: 'BN rom 11', text: "chai ta bahut bhalo hoyeche aro ektu chini dile aro bhalo hobe", expectRomanized: true },
  { label: 'BN rom 12', text: "porikkhar jonno onek poraashona korte hobe noyto result bhalo hobe na", expectRomanized: true },
  { label: 'BN rom 13', text: "aaj shandhe te amar bondhu der shathe adda debo bahut din hoye gache", expectRomanized: true },
  { label: 'BN rom 14', text: "padma nodir dhare boshe thakle onek shanti lagche mon ta bhalo hoye jaay", expectRomanized: true },
  { label: 'BN rom 15', text: "bikel bela cha mishti khele onek bhalo lagche shobar shathe guppo kori", expectRomanized: true },
  { label: 'BN rom 16', text: "rickshaw te kore bazaar jete hobe shobji aur mach kinte shobkichhu", expectRomanized: true },
  { label: 'BN rom 17', text: "tomar bhai kemon ache shob bhalo to toke onek miss korchi", expectRomanized: true },
  { label: 'BN rom 18', text: "rabindranath thakurer kobita shune mon ta bhore jaay ki adbhut lekha", expectRomanized: true },

  // ═══ Tamil romanized ═══
  { label: 'TA rom 1', text: "naan innikku school poga villai romba kashtam irukku ennala mudiyala", expectRomanized: true },
  { label: 'TA rom 2', text: "amma samayal pannunga naan varrein konjam wait pannunga inga irukken", expectRomanized: true },
  { label: 'TA rom 3', text: "vanakkam eppadi irukkinga naan nalla irukken nandri ungalukku", expectRomanized: true },
  { label: 'TA rom 4', text: "innikku mazhai varum pola irukku kudai eduthukkonga veliya poga", expectRomanized: true },
  { label: 'TA rom 5', text: "naan romba tired ah irukken innikku office la romba velai irunthathu", expectRomanized: true },
  { label: 'TA rom 6', text: "enna panreenga innikku naan ungala parkka vanthen eppadi irukkinga", expectRomanized: true },
  { label: 'TA rom 7', text: "filter kaapi kudicha romba nalla irukku morning la kudicha super", expectRomanized: true },
  { label: 'TA rom 8', text: "idli sambar dosa chutney romba nalla irukku enoda favourite food", expectRomanized: true },
  { label: 'TA rom 9', text: "temple ku poga lazim innikku pooja irukku amma sollunga vanga", expectRomanized: true },
  { label: 'TA rom 10', text: "cricket match paatheenga la india nalla vilayaaduchi romba happy", expectRomanized: true },
  { label: 'TA rom 11', text: "naan padikkanum exam varumae konjam time kudunga please romba mukkiyam", expectRomanized: true },
  { label: 'TA rom 12', text: "marina beach la poi walking pannalaam sandhai neeram romba nalla irukku", expectRomanized: true },
  { label: 'TA rom 13', text: "ungaloda phone number kudunga naan call pannuren naalaikki", expectRomanized: true },
  { label: 'TA rom 14', text: "pongal pandigai la pudhu veshti poduvom sakkarai pongal pannuvom", expectRomanized: true },
  { label: 'TA rom 15', text: "bus la poi varrein romba crowd irukku innikku traffic um romba", expectRomanized: true },

  // ═══ Thai romanized ═══
  { label: 'TH rom 1', text: "wan nee pai talad mai kha yak sue khong krap sabai dee", expectRomanized: true },
  { label: 'TH rom 2', text: "phom chob ahan thai mak krap aroy mak mak kin mai mot", expectRomanized: true },
  { label: 'TH rom 3', text: "sawadee krap khun sabai dee mai krap wan nee akat dee mak", expectRomanized: true },
  { label: 'TH rom 4', text: "pai thiao kan mai krap wan nee arai dee arai naa sanuk", expectRomanized: true },
  { label: 'TH rom 5', text: "khob khun mak krap thi chuai phom wan nee yin dee mak", expectRomanized: true },
  { label: 'TH rom 6', text: "ahan pad thai aroy mak krap gin kap bia leo kin khao", expectRomanized: true },
  { label: 'TH rom 7', text: "phom rak khun mak kha khun suai mak wan nee pen wan dee", expectRomanized: true },
  { label: 'TH rom 8', text: "phrung nee tong pai tham ngan krap tuen chao mak mai dai", expectRomanized: true },
  { label: 'TH rom 9', text: "muang thai suai mak krap khon thai jai dee mak yin dee", expectRomanized: true },
  { label: 'TH rom 10', text: "rot tit mak wan nee krap pai nai ko mai sa duak loei", expectRomanized: true },
  { label: 'TH rom 11', text: "naam phrik aroy mak gin kap khao suai mai dai kin maak", expectRomanized: true },
  { label: 'TH rom 12', text: "songkran sanuk mak mak krap len naam kan thang wan sabai", expectRomanized: true },

  // ═══ Persian/Farsi romanized ═══
  { label: 'FA rom 1', text: "man daram miram khaneh kheili khasteh hastam emruz az sobh", expectRomanized: true },
  { label: 'FA rom 2', text: "farda bayad beram daneshgah emtehan daram sobh zud bayad bidaram", expectRomanized: true },
  { label: 'FA rom 3', text: "salam chetori halet khube man khubam merci doost az didanet", expectRomanized: true },
  { label: 'FA rom 4', text: "ghaza kheili khoshmazeh bud daste shoma dard nakone merci", expectRomanized: true },
  { label: 'FA rom 5', text: "emruz hava kheili garme birun narim behtar as khaneh bashe", expectRomanized: true },
  { label: 'FA rom 6', text: "ketab khundan kheili khube man har ruz ketab mikhunam shab ha", expectRomanized: true },
  { label: 'FA rom 7', text: "bazaar raftam meeveh kharidamar sabzi ham kharidamar baraye shab", expectRomanized: true },
  { label: 'FA rom 8', text: "norouz mobarak sale no pirouz omidvaram sal khobi dashte bashin", expectRomanized: true },
  { label: 'FA rom 9', text: "tehran kheili sholughe traffic ziyade kheili vaght mibare rafte", expectRomanized: true },
  { label: 'FA rom 10', text: "man ashpazi balad nistam vali mikham yad begiram az madar", expectRomanized: true },
  { label: 'FA rom 11', text: "chai irani kheili khoshmazeh hast ba nabat ya shakar mikhoram", expectRomanized: true },
  { label: 'FA rom 12', text: "doostam zang zad goft farda biyad khanash mehmuni dare shab", expectRomanized: true },

  // ═══ Telugu romanized ═══
  { label: 'TE rom 1', text: "nenu intiki veltunnanu ma amma kosam chala dooram nundi vastunna", expectRomanized: true },
  { label: 'TE rom 2', text: "meeru ela unnaru chala rojulu ayyindi kalavadaniki chala santosham", expectRomanized: true },
  { label: 'TE rom 3', text: "ippudu bhojananiki veldama naku chala aakali vestundi bayata veldama", expectRomanized: true },
  { label: 'TE rom 4', text: "nenu telugu paatalu vinnanu chala baagunnaayi mee gurinci cheppandi", expectRomanized: true },
  { label: 'TE rom 5', text: "rendu chai lu teesukorandi chala manchidi ee chai shop lo", expectRomanized: true },
  { label: 'TE rom 6', text: "maa nanna chala manchivadu andari ki sahayam chestadu yeppudu", expectRomanized: true },
  { label: 'TE rom 7', text: "nenu chaduvutunnanu exam kosam chala kashtam ga prepare avutunna", expectRomanized: true },
  { label: 'TE rom 8', text: "hyderabad lo biryani chala famous dum biryani tinte chala baaguntadi", expectRomanized: true },
  { label: 'TE rom 9', text: "sankranthi pandaga lo memu rangoli vestamu pongali chestamu inti daggara", expectRomanized: true },
  { label: 'TE rom 10', text: "cinema chudadaniki veldama kontha sepu aagandi nenu vastunna ippudu", expectRomanized: true },

  // ═══ Vietnamese without diacritics ═══
  { label: 'VI noa 1', text: "toi muon di an com voi ban toi hom nay troi dep lam qua", expectRomanized: true },
  { label: 'VI noa 2', text: "hom nay troi mua to lam toi o nha doc sach ca ngay", expectRomanized: true },
  { label: 'VI noa 3', text: "chung toi di hoc moi ngay truong hoc rat tot ban be nhieu", expectRomanized: true },
  { label: 'VI noa 4', text: "me toi nau an rat ngon hom nay com chien va canh chua", expectRomanized: true },
  { label: 'VI noa 5', text: "xin chao ban khoe khong toi rat vui duoc gap ban hom nay", expectRomanized: true },
  { label: 'VI noa 6', text: "toi thich uong ca phe viet nam moi sang toi deu uong mot ly", expectRomanized: true },
  { label: 'VI noa 7', text: "ha noi la thu do cua viet nam co nhieu noi dep de di choi", expectRomanized: true },
  { label: 'VI noa 8', text: "tet nguyen dan la ngay le lon nhat cua nguoi viet nam chuc mung", expectRomanized: true },

  // ═══ Nepali romanized ═══
  { label: 'NE rom 1', text: "tapai kasto hunuhunchha ma thik chhu dhanyabaad hajur aaja ramro din", expectRomanized: true },
  { label: 'NE rom 2', text: "nepal dherai ramro desh ho himaal haru dherai sundar chhan yahan", expectRomanized: true },
  { label: 'NE rom 3', text: "mero ghar pokhara ma chha wahaan ko taal dherai ramro chha", expectRomanized: true },
  { label: 'NE rom 4', text: "bholi bihaana school jaanu parchha kitab haru tayar garnuhos aaja", expectRomanized: true },
  { label: 'NE rom 5', text: "daal bhaat tarkari khaana man lagyo aama le ramro pakaun bhayo", expectRomanized: true },

  // ═══ Gujarati romanized ═══
  { label: 'GU rom 1', text: "kem cho tamne joi ne khushi thai mane bahut maja aavi aaj", expectRomanized: true },
  { label: 'GU rom 2', text: "aaje garmi bahut chhe bahar nikalne nu mann nathi thay haju", expectRomanized: true },
  { label: 'GU rom 3', text: "dhokla ne jalebi khavanu mann thay che chalo bazaar jaiye sathe", expectRomanized: true },
  { label: 'GU rom 4', text: "navratri ma raas garba ramva jaiye bahut maja aave che tyare", expectRomanized: true },
  { label: 'GU rom 5', text: "bhai tamaru kaam ketlu thayu aaje office mathi vahelu aavo ghar pe", expectRomanized: true },
];
